name: Github Pages Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Odin
        uses: laytan/setup-odin@v2

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Web
        run: ./build_web.sh
